services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-api:
    build:
      context: .
      dockerfile: core-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DB_PATH=/data/banco.db
    volumes:
      - banco_data:/data

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DB_PATH=/data/banco.db
    volumes:
      - banco_data:/data

volumes:
  banco_data: